#table main activity column
TABLE_ID				= 0
TABLE_CANBEINTERRUPTED	= TABLE_CANINTERRUPT + 1
TABLE_STARTTIMECANSTART	= TABLE_CANBEINTERRUPTED + 1
TABLE_ENDTIMECANSTART	= TABLE_STARTTIMECANSTART + 1
TABLE_DURATION			= TABLE_ENDTIMECANSTART + 1
TABLE_ROOM1				= TABLE_DURATION + 1
TABLE_ROOM2				= TABLE_ROOM1 + 1
TABLE_PLAN				= TABLE_ROOM2 + 1
TABLE_HABIT				= TABLE_PLAN + 1
TABLE_RULES				= TABLE_HABIT + 1
TABLE_EXHAUST			= TABLE_RULES + 1
TABLE_SLEEPY			= TABLE_EXHAUST + 1
TABLE_DIRTY				= TABLE_SLEEPY + 1
TABLE_URINATE			= TABLE_DIRTY + 1
TABLE_DEFECATE			= TABLE_URINATE + 1
TABLE_ENERGY			= TABLE_DEFECATE + 1
TABLE_HUNGER			= TABLE_ENERGY + 1
TABLE_THIRSTY			= TABLE_HUNGER + 1
TABLE_ABILITY			= TABLE_THIRSTY + 1
TABLE_STRESS			= TABLE_ABILITY + 1
TABLE_EMOTION			= TABLE_STRESS + 1
TABLE_MOOD				= TABLE_EMOTION + 1
TABLE_LONELINESS		= TABLE_MOOD + 1
TABLE_COLUMN_COUNT		= TABLE_LONELINESS + 1

#table support activity column
TABLE_SA_ID		= 0
TABLE_SA_HABIT	= TABLE_SA_ID + 1

#table terms column
TABLE_TERM_ID					= 0
TABLE_TERM_ABILITY				= TABLE_TERM_ID + 1
TABLE_TERM_LIGHT				= TABLE_TERM_ABILITY + 1
TABLE_TERM_LIGHTOBJECT			= TABLE_TERM_LIGHT + 1
TABLE_TERM_TEMPERATURE			= TABLE_TERM_LIGHTOBJECT + 1
TABLE_TERM_TEMPERATUREOBJECT	= TABLE_TERM_TEMPERATURE + 1
TABLE_TERM_RESOURCE1			= TABLE_TERM_TEMPERATUREOBJECT + 1
TABLE_TERM_FAILRESOURCE1		= TABLE_TERM_RESOURCE1 + 1
TABLE_TERM_RESOURCE1OBJECT		= TABLE_TERM_FAILRESOURCE1 + 1
TABLE_TERM_RESOURCE2			= TABLE_TERM_RESOURCE1OBJECT + 1
TABLE_TERM_FAILRESOURCE2		= TABLE_TERM_RESOURCE2 + 1
TABLE_TERM_RESOURCE2OBJECT		= TABLE_TERM_FAILRESOURCE2 + 1
TABLE_TERM_ROOMFACTOR1			= TABLE_TERM_RESOURCE2OBJECT + 1
TABLE_TERM_FAILROOMFACTOR1		= TABLE_TERM_ROOMFACTOR1 + 1
TABLE_TERM_ROOMFACTOR2			= TABLE_TERM_FAILROOMFACTOR1 + 1
TABLE_TERM_FAILROOMFACTOR2		= TABLE_TERM_ROOMFACTOR2 + 1
TABLE_TERM_ROOMPRIO1			= TABLE_TERM_FAILROOMFACTOR2 + 1
TABLE_TERM_ROOMPRIO2			= TABLE_TERM_ROOMPRIO1 + 1

#environment terms for activity
TERM_ENVI_LIGHT			= 0
TERM_ENVI_TEMPERATURE	= TERM_ENVI_LIGHT + 1
TERM_ENVI_TOTAL			= TERM_ENVI_TEMPERATURE + 1

TERM_ENVI_AFFECT	= 0
TERM_ENVI_OBJECT	= TERM_ENVI_AFFECT + 1

#resource object field
RES_TYPE			= 0
RES_FAILACTIVITY	= RES_TYPE + 1
RES_OBJECT			= RES_FAILACTIVITY + 1

RES_COUNT			= 2

#resource type enum
RES_WATER		= 0
RES_ELECTRICITY	= RES_WATER + 1
RES_GAS			= RES_ELECTRICITY + 1
RES_FOOD		= RES_GAS + 1
RES_FOOD_MTRIAL	= RES_FOOD + 1
RES_READ_MTRIAL	= RES_FOOD_MTRIAL + 1
RES_TOTAL		= RES_READ_MTRIAL + 1

#room factor enum
RF_CHAIR			= 0
RF_SOFA				= RF_CHAIR + 1
RF_CARPET			= RF_SOFA + 1
RF_DOOR				= RF_CARPET + 1
RF_BED				= RF_DOOR + 1
RF_CLEANING_UTLTY	= RF_BED + 1
RF_TOTAL			= RF_CLEANING_UTLTY + 1

RF_COUNT			= 2

def ResourceToID(res):
	resLowerCase = res.lower()
	if resLowerCase == "water":
		return RES_WATER
	elif resLowerCase == "electricity"
		return RES_ELECTRICITY
	elif resLowerCase == "gas"
		return RES_GAS
	elif resLowerCase == "food"
		return RES_FOOD
	elif resLowerCase == "food material"
		return RES_FOOD_MTRIAL
	else
		return RES_READ_MTRIAL

def RoomFactorToID(roomF):
	rFactorLowerCase = roomF.lower()
	if rFactorLowerCase == "chair":
		return RF_CHAIR
	elif rFactorLowerCase == "sofa":
		return RF_SOFA
	elif rFactorLowerCase == "carpet":
		return RF_CARPET
	elif rFactorLowerCase == "door":
		return RF_DOOR
	elif rFactorLowerCase == "bed":
		return RF_BED
	else:
		return RF_CLEANING_UTLTY
