#table main activity column
TABLE_ACTIVITY_ID					= 0
TABLE_ACTIVITY_CHANCE				= TABLE_ACTIVITY_ID + 1
TABLE_ACTIVITY_CANINTERRUPT			= TABLE_ACTIVITY_CHANCE + 1
TABLE_ACTIVITY_CANBEINTERRUPTED		= TABLE_ACTIVITY_CANINTERRUPT + 1
TABLE_ACTIVITY_STARTTIMECANSTART	= TABLE_ACTIVITY_CANBEINTERRUPTED + 1
TABLE_ACTIVITY_ENDTIMECANSTART		= TABLE_ACTIVITY_STARTTIMECANSTART + 1
TABLE_ACTIVITY_DURATION				= TABLE_ACTIVITY_ENDTIMECANSTART + 1
TABLE_ACTIVITY_PLAN					= TABLE_ACTIVITY_DURATION + 1
TABLE_ACTIVITY_HABIT				= TABLE_ACTIVITY_PLAN + 1
TABLE_ACTIVITY_AUTHORITY			= TABLE_ACTIVITY_HABIT + 1
TABLE_ACTIVITY_OBEDIENCE			= TABLE_ACTIVITY_AUTHORITY + 1
TABLE_ACTIVITY_EXHAUST				= TABLE_ACTIVITY_OBEDIENCE + 1
TABLE_ACTIVITY_SLEEPY				= TABLE_ACTIVITY_EXHAUST + 1
TABLE_ACTIVITY_DIRTY				= TABLE_ACTIVITY_SLEEPY + 1
TABLE_ACTIVITY_URINATE				= TABLE_ACTIVITY_DIRTY + 1
TABLE_ACTIVITY_DEFECATE				= TABLE_ACTIVITY_URINATE + 1
TABLE_ACTIVITY_ENERGY				= TABLE_ACTIVITY_DEFECATE + 1
TABLE_ACTIVITY_HUNGER				= TABLE_ACTIVITY_ENERGY + 1
TABLE_ACTIVITY_THIRSTY				= TABLE_ACTIVITY_HUNGER + 1
TABLE_ACTIVITY_ABILITY				= TABLE_ACTIVITY_THIRSTY + 1
TABLE_ACTIVITY_STRESS				= TABLE_ACTIVITY_ABILITY + 1
TABLE_ACTIVITY_EMOTION				= TABLE_ACTIVITY_STRESS + 1
TABLE_ACTIVITY_MOOD					= TABLE_ACTIVITY_EMOTION + 1
TABLE_ACTIVITY_LONELINESS			= TABLE_ACTIVITY_MOOD + 1
TABLE_ACTIVITY_COLUMN_COUNT			= TABLE_ACTIVITY_LONELINESS + 1

INTERRUPT_CAN_INTERRUPT				= 0
INTERRUPT_CAN_BE_INTERRUPTED		= INTERRUPT_CAN_INTERRUPT + 1
INTERRUPT_PROPERTY_COUNT			= INTERRUPT_CAN_BE_INTERRUPTED + 1

TIME_PROPERTY_STARTTIME_CANSTART	= 0
TIME_PROPERTY_ENDTIME_CANSTART		= TIME_PROPERTY_STARTTIME_CANSTART + 1
TIME_PROPERTY_DURATION				= TIME_PROPERTY_ENDTIME_CANSTART + 1
TIME_PROPERTY_COUNT					= TIME_PROPERTY_DURATION + 1

PLAN_PROPERTY_COUNT					= 3

BIOLOGICAL_PROPERTY_EXHAUST			= 0
BIOLOGICAL_PROPERTY_SLEEPY			= BIOLOGICAL_PROPERTY_EXHAUST + 1
BIOLOGICAL_PROPERTY_DIRTY			= BIOLOGICAL_PROPERTY_SLEEPY + 1
BIOLOGICAL_PROPERTY_URINATE			= BIOLOGICAL_PROPERTY_DIRTY + 1
BIOLOGICAL_PROPERTY_DEFECATE		= BIOLOGICAL_PROPERTY_URINATE + 1
BIOLOGICAL_PROPERTY_ENERGY			= BIOLOGICAL_PROPERTY_DEFECATE + 1
BIOLOGICAL_PROPERTY_HUNGER			= BIOLOGICAL_PROPERTY_ENERGY + 1
BIOLOGICAL_PROPERTY_THIRSTY			= BIOLOGICAL_PROPERTY_HUNGER + 1
BIOLOGICAL_PROPERTY_ABILITY			= BIOLOGICAL_PROPERTY_THIRSTY + 1
BIOLOGICAL_PROPERTY_COUNT			= BIOLOGICAL_PROPERTY_ABILITY + 1

ES_PROPERTY_STRESS					= 0
ES_PROPERTY_EMOTION					= ES_PROPERTY_STRESS + 1
ES_PROPERTY_MOOD					= ES_PROPERTY_EMOTION + 1
ES_PROPERTY_LONELINESS				= ES_PROPERTY_MOOD + 1
ES_PROPERTY_COUNT					= ES_PROPERTY_LONELINESS + 1

#table support activity column
TABLE_SA_ID			= 0
TABLE_SA_HABIT		= TABLE_SA_ID + 1
TABLE_SA_DURATION	= TABLE_SA_HABIT + 1

#table terms column
TABLE_TERM_ID					= 0
TABLE_TERM_ABILITY				= TABLE_TERM_ID + 1
TABLE_TERM_LIGHT				= TABLE_TERM_ABILITY + 1
TABLE_TERM_LIGHTOBJECT			= TABLE_TERM_LIGHT + 1
TABLE_TERM_TEMPERATURE			= TABLE_TERM_LIGHTOBJECT + 1
TABLE_TERM_TEMPERATUREOBJECT	= TABLE_TERM_TEMPERATURE + 1
TABLE_TERM_RESOURCE1			= TABLE_TERM_TEMPERATUREOBJECT + 1
TABLE_TERM_FAILRESOURCE1		= TABLE_TERM_RESOURCE1 + 1
TABLE_TERM_RESOURCE1OBJECT		= TABLE_TERM_FAILRESOURCE1 + 1
TABLE_TERM_RESOURCE2			= TABLE_TERM_RESOURCE1OBJECT + 1
TABLE_TERM_FAILRESOURCE2		= TABLE_TERM_RESOURCE2 + 1
TABLE_TERM_RESOURCE2OBJECT		= TABLE_TERM_FAILRESOURCE2 + 1
TABLE_TERM_ROOMFACTOR1			= TABLE_TERM_RESOURCE2OBJECT + 1
TABLE_TERM_FAILROOMFACTOR1		= TABLE_TERM_ROOMFACTOR1 + 1
TABLE_TERM_ROOMFACTOR2			= TABLE_TERM_FAILROOMFACTOR1 + 1
TABLE_TERM_FAILROOMFACTOR2		= TABLE_TERM_ROOMFACTOR2 + 1
TABLE_TERM_ROOMPRIO1			= TABLE_TERM_FAILROOMFACTOR2 + 1
TABLE_TERM_ROOMPRIO2			= TABLE_TERM_ROOMPRIO1 + 1

#table initial condition and rate
TABLE_IC_ROLE				= 0
TABLE_IC_IC_BIO_START		= TABLE_IC_ROLE + 1
TABLE_IC_BIO_RATE_START		= TABLE_IC_IC_BIO_START + BIOLOGICAL_PROPERTY_COUNT
TABLE_IC_IC_ES_START		= TABLE_IC_BIO_RATE_START + BIOLOGICAL_PROPERTY_COUNT
TABLE_IC_ES_RATE_START		= TABLE_IC_IC_ES_START + ES_PROPERTY_COUNT
TABLE_IC_COUNT				= TABLE_IC_BIO_RATE_START + ES_PROPERTY_COUNT

#environment terms for activity
TERM_ENVI_LIGHT			= 0
TERM_ENVI_TEMPERATURE	= TERM_ENVI_LIGHT + 1
TERM_ENVI_TOTAL			= TERM_ENVI_TEMPERATURE + 1

TERM_ENVI_AFFECT	= 0
TERM_ENVI_OBJECT	= TERM_ENVI_AFFECT + 1

#resource object field
RES_TYPE			= 0
RES_FAILACTIVITY	= RES_TYPE + 1
RES_OBJECT			= RES_FAILACTIVITY + 1

RES_COUNT			= 2

#resource type enum
RES_WATER		= 0
RES_ELECTRICITY	= RES_WATER + 1
RES_GAS			= RES_ELECTRICITY + 1
RES_FOOD		= RES_GAS + 1
RES_FOOD_MTRIAL	= RES_FOOD + 1
RES_READ_MTRIAL	= RES_FOOD_MTRIAL + 1
RES_TOTAL		= RES_READ_MTRIAL + 1

#room factor enum
RF_CHAIR			= 0
RF_SOFA				= RF_CHAIR + 1
RF_CARPET			= RF_SOFA + 1
RF_DOOR				= RF_CARPET + 1
RF_BED				= RF_DOOR + 1
RF_CLEANING_UTLTY	= RF_BED + 1
RF_TOTAL			= RF_CLEANING_UTLTY + 1

RF_COUNT			= 2

#room prio
ROOM_PRIO_COUNT 	= 2

def ResourceToID(res):
	resLowerCase = res.lower()
	if resLowerCase == "water":
		return RES_WATER
	elif resLowerCase == "electricity":
		return RES_ELECTRICITY
	elif resLowerCase == "gas":
		return RES_GAS
	elif resLowerCase == "food":
		return RES_FOOD
	elif resLowerCase == "food material":
		return RES_FOOD_MTRIAL
	else:
		return RES_READ_MTRIAL

def RoomFactorToID(roomF):
	rFactorLowerCase = roomF.lower()
	if rFactorLowerCase == "chair":
		return RF_CHAIR
	elif rFactorLowerCase == "sofa":
		return RF_SOFA
	elif rFactorLowerCase == "carpet":
		return RF_CARPET
	elif rFactorLowerCase == "door":
		return RF_DOOR
	elif rFactorLowerCase == "bed":
		return RF_BED
	else:
		return RF_CLEANING_UTLTY
