"""
Constants that used across simulation component
"""
EFFECT_NEW_LIMIT		= 0
EFFECT_NEW_VALUE		= EFFECT_NEW_LIMIT + 1

EFFECT_HABIT_NONHABIT	= 0
EFFECT_HABIT_HABIT		= EFFECT_HABIT_NONHABIT + 1
EFFECT_EAT				= EFFECT_HABIT_HABIT + 1 #for Thirst property only

EFFECT_HUNGER_EAT		= 0
EFFECT_HUNGER_NONEAT	= EFFECT_HUNGER_EAT + 1

EFFECT_URINATE_NORMAL	= 0
EFFECT_URINATE_DEFECATE	= EFFECT_URINATE_NORMAL + 1

EFFECT_HOUR_START		= 0
EFFECT_HOUR_END			= EFFECT_HOUR_START + 1
EFFECT_LIMIT_DOWN		= EFFECT_HOUR_END + 1
EFFECT_LIMIT_UP			= EFFECT_LIMIT_DOWN + 1
EFFECT_VALUE			= EFFECT_LIMIT_UP + 1
EFFECT_COUNT			= EFFECT_VALUE + 1

EFFECT_TIMEBASED_HOUR_START		= 0
EFFECT_TIMEBASED_HOUR_END		= EFFECT_TIMEBASED_HOUR_START + 1
EFFECT_TIMEBASED_LIMIT_DOWN		= EFFECT_TIMEBASED_HOUR_END + 1
EFFECT_TIMEBASED_LIMIT_UP		= EFFECT_TIMEBASED_LIMIT_DOWN + 1
EFFECT_TIMEBASED_VALUE			= EFFECT_TIMEBASED_LIMIT_UP + 1
EFFECT_TIMEBASED_COUNT			= EFFECT_TIMEBASED_VALUE + 1

FORMAT_TIME_HOUR		= 0
FORMAT_TIME_MINUTE		= FORMAT_TIME_HOUR + 1

#for actor bio property
IC_PROPERTY				= 0
IC_CURRENT				= IC_PROPERTY + 1
IC_RATE					= IC_CURRENT + 1
IC_HABIT				= IC_RATE + 1
IC_EFFECT				= IC_HABIT + 1
IC_CUSTOM				= IC_EFFECT + 1
IC_DURATION				= IC_CUSTOM + 1
#for actor other initial condition
IC_VALUE				= IC_PROPERTY + 1

RATE_TOBLADDER			= 0
RATE_TOPEE				= RATE_TOBLADDER + 1

BIOLOGICAL_PROPERTY_HUNGER			= 0
BIOLOGICAL_PROPERTY_DIRTY			= BIOLOGICAL_PROPERTY_HUNGER + 1
BIOLOGICAL_PROPERTY_THIRSTY			= BIOLOGICAL_PROPERTY_DIRTY + 1
BIOLOGICAL_PROPERTY_ENERGY			= BIOLOGICAL_PROPERTY_THIRSTY + 1
BIOLOGICAL_PROPERTY_TIRED			= BIOLOGICAL_PROPERTY_ENERGY + 1
BIOLOGICAL_PROPERTY_SLEEPY			= BIOLOGICAL_PROPERTY_TIRED + 1
BIOLOGICAL_PROPERTY_DEFECATE		= BIOLOGICAL_PROPERTY_SLEEPY + 1
BIOLOGICAL_PROPERTY_URINATE			= BIOLOGICAL_PROPERTY_DEFECATE + 1
BIOLOGICAL_PROPERTY_COUNT			= BIOLOGICAL_PROPERTY_URINATE + 1

PLAN_PROPERTY_WISH			= 0
PLAN_PROPERTY_ADVANTAGE		= PLAN_PROPERTY_WISH + 1
PLAN_PROPERTY_AUTHORITY		= PLAN_PROPERTY_ADVANTAGE + 1
PLAN_PROPERTY_OBEDIENCE		= PLAN_PROPERTY_AUTHORITY + 1
PLAN_PROPERTY_URGENCY			= PLAN_PROPERTY_OBEDIENCE + 1
PLAN_PROPERTY_COUNT			= PLAN_PROPERTY_URGENCY + 1

TABLE_ACTIVITY_ID						= 0
TABLE_ACTIVITY_DESC						= TABLE_ACTIVITY_ID + 1
TABLE_ACTIVITY_REPEAT					= TABLE_ACTIVITY_DESC + 1
TABLE_ACTIVITY_AUTO						= TABLE_ACTIVITY_REPEAT + 1
TABLE_ACTIVITY_OUTDOOR					= TABLE_ACTIVITY_AUTO + 1
TABLE_ACTIVITY_BIOACTIVITY				= TABLE_ACTIVITY_OUTDOOR + 1
TABLE_ACTIVITY_INTERRUPT				= TABLE_ACTIVITY_BIOACTIVITY + 1
TABLE_ACTIVITY_BIO_EFFECT_START			= TABLE_ACTIVITY_INTERRUPT + 1
TABLE_ACTIVITY_EMO_EFFECT				= TABLE_ACTIVITY_BIO_EFFECT_START + BIOLOGICAL_PROPERTY_COUNT
TABLE_ACTIVITY_DURATION					= TABLE_ACTIVITY_EMO_EFFECT + 1
TABLE_ACTIVITY_START					= TABLE_ACTIVITY_DURATION + 1
TABLE_ACTIVITY_PRIORITY					= TABLE_ACTIVITY_START + 1
TABLE_ACTIVITY_PHY_STD					= TABLE_ACTIVITY_PRIORITY + 1
TABLE_ACTIVITY_PLAN_START				= TABLE_ACTIVITY_PHY_STD + 1
TABLE_ACTIVITY_ROUTINE					= TABLE_ACTIVITY_PLAN_START + PLAN_PROPERTY_COUNT
TABLE_ACTIVITY_PREQUISITE				= TABLE_ACTIVITY_ROUTINE + 1
TABLE_ACTIVITY_INTERACT_AGENT			= TABLE_ACTIVITY_PREQUISITE + 1
TABLE_ACTIVITY_FOLLOWER_ACTIVITY		= TABLE_ACTIVITY_INTERACT_AGENT + 1
TABLE_ACTIVITY_FOLLOW_MOVEMENT			= TABLE_ACTIVITY_FOLLOWER_ACTIVITY + 1
TABLE_ACTIVITY_SET						= TABLE_ACTIVITY_FOLLOW_MOVEMENT + 1
TABLE_ACTIVITY_NEXT_ACTIVITY			= TABLE_ACTIVITY_SET + 1
TABLE_ACTIVITY_ELIMINATE_ACTIVITY		= TABLE_ACTIVITY_NEXT_ACTIVITY + 1
TABLE_ACTIVITY_ROOM						= TABLE_ACTIVITY_ELIMINATE_ACTIVITY + 1
TABLE_ACTIVITY_DOOR						= TABLE_ACTIVITY_ROOM + 1
TABLE_ACTIVITY_LIGHTTHRESHOLD			= TABLE_ACTIVITY_DOOR + 1
TABLE_ACTIVITY_STATUS					= TABLE_ACTIVITY_LIGHTTHRESHOLD + 1
TABLE_ACTIVITY_TEMPERATURE				= TABLE_ACTIVITY_STATUS + 1
TABLE_ACTIVITY_DEVICE					= TABLE_ACTIVITY_TEMPERATURE + 1
TABLE_ACTIVITY_POST_ACTIVITY			= TABLE_ACTIVITY_DEVICE + 1
TABLE_ACTIVITY_RESOURCE					= TABLE_ACTIVITY_POST_ACTIVITY + 1
TABLE_ACTIVITY_INTERACTAGENTSTATUS		= TABLE_ACTIVITY_RESOURCE + 1
TABLE_ACTIVITY_URGENCY_TYPE				= TABLE_ACTIVITY_INTERACTAGENTSTATUS + 1
TABLE_ACTIVITY_URGENCY_VALUE			= TABLE_ACTIVITY_URGENCY_TYPE + 1
TABLE_ACTIVITY_EFFECT					= TABLE_ACTIVITY_URGENCY_VALUE + 1
TABLE_ACTIVITY_COUNT					= TABLE_ACTIVITY_EFFECT + 1

ACT_EFFECT_RUN			= 0
ACT_EFFECT_STD			= ACT_EFFECT_RUN + 1

EMO_EFFECT_RUN			= 0
EMO_EFFECT_SUSPEND		= EMO_EFFECT_RUN + 1
EMO_EFFECT_STD			= EMO_EFFECT_SUSPEND + 1

TERM_LIGHT				= 0
TERM_STATUS				= TERM_LIGHT + 1
TERM_TEMPERATURE		= TERM_STATUS + 1
TERM_COUNT				= TERM_TEMPERATURE + 1

ACT_STATUS_NONE		= 0
ACT_STATUS_GOTO		= ACT_STATUS_NONE + 1
ACT_STATUS_RUN		= ACT_STATUS_GOTO + 1
ACT_STATUS_SUSPEND	= ACT_STATUS_RUN + 1
ACT_STATUS_PAUSED	= ACT_STATUS_SUSPEND + 1

AGENT_AWAKE			= 0
AGENT_ASLEEP		= AGENT_AWAKE + 1
AGENT_CUST_COND		= AGENT_ASLEEP + 1
AGENT_CUST_COND2	= AGENT_CUST_COND + 1
RATE_BASE			= AGENT_CUST_COND2 + 1
RATE_DIVIDER		= RATE_BASE + 1

HUNGER_LIMIT_DOWN	= 0
HUNGER_LIMIT_UP		= HUNGER_LIMIT_DOWN + 1

ENERGY_TYPE_ELECTRICITY	= 0
ENERGY_TYPE_WATER		= ENERGY_TYPE_ELECTRICITY + 1
ENERGY_TYPE_GAS			= ENERGY_TYPE_WATER + 1

EFFECT_LIGHT		= 0
EFFECT_TEMPERATURE	= EFFECT_LIGHT + 1

INT_CAN_BE_INTERRUPTED	= 0
INT_CAN_INTERRUPT		= INT_CAN_BE_INTERRUPTED + 1

RES_NOGENERAL			= 0
RES_GENERAL				= RES_NOGENERAL + 1
RES_GENERAL_TYPE2		= RES_GENERAL + 1

ACT_TABLE_LOG_KEY					= 0
ACT_TABLE_LOG_INDEX					= ACT_TABLE_LOG_KEY + 1
ACT_TABLE_LOG_TIME					= ACT_TABLE_LOG_INDEX + 1
ACT_TABLE_LOG_SCORE					= ACT_TABLE_LOG_TIME + 1
ACT_TABLE_LOG_MOVE_TO				= ACT_TABLE_LOG_SCORE + 1
ACT_TABLE_LOG_INCIDENTAL			= ACT_TABLE_LOG_MOVE_TO + 1
ACT_TABLE_LOG_INCIDENTALTIME		= ACT_TABLE_LOG_INCIDENTAL + 1
ACT_TABLE_LOG_SWITCH_TO				= ACT_TABLE_LOG_INCIDENTALTIME + 1
ACT_TABLE_LOG_AGENT_INCIDENTAL		= ACT_TABLE_LOG_SWITCH_TO + 1
ACT_TABLE_LOG_TIMERANGE				= ACT_TABLE_LOG_AGENT_INCIDENTAL + 1
ACT_TABLE_LOG_CURRENT_ACT			= ACT_TABLE_LOG_TIMERANGE + 1
ACT_TABLE_LOG_INITIATOR				= ACT_TABLE_LOG_CURRENT_ACT + 1
ACT_TABLE_LOG_WISH_TOTAL			= ACT_TABLE_LOG_INITIATOR + 1
ACT_TABLE_LOG_WISH_SN				= ACT_TABLE_LOG_WISH_TOTAL + 1
ACT_TABLE_LOG_WISH_EMO				= ACT_TABLE_LOG_WISH_SN + 1
ACT_TABLE_LOG_ADV_TOTAL				= ACT_TABLE_LOG_WISH_EMO + 1
ACT_TABLE_LOG_ADV_SN				= ACT_TABLE_LOG_ADV_TOTAL + 1
ACT_TABLE_LOG_ADV_MATRIX			= ACT_TABLE_LOG_ADV_SN + 1
ACT_TABLE_LOG_RULE_TOTAL			= ACT_TABLE_LOG_ADV_MATRIX + 1
ACT_TABLE_LOG_RULE_AUTHORITY		= ACT_TABLE_LOG_RULE_TOTAL + 1
ACT_TABLE_LOG_RULE_OBEDIENCE		= ACT_TABLE_LOG_RULE_AUTHORITY + 1
ACT_TABLE_LOG_URG_TOTAL				= ACT_TABLE_LOG_RULE_OBEDIENCE + 1
ACT_TABLE_LOG_URG_CUR_AGT_SN		= ACT_TABLE_LOG_URG_TOTAL + 1
ACT_TABLE_LOG_URG_CUR_AGT_CLEAN		= ACT_TABLE_LOG_URG_CUR_AGT_SN + 1
ACT_TABLE_LOG_URG_OTHER_AGT_START	= ACT_TABLE_LOG_URG_CUR_AGT_CLEAN + 1
ACT_TABLE_LOG_HR_FLOORSTATUS		= ACT_TABLE_LOG_URG_OTHER_AGT_START + (4 * 2) + 1 # 4 agent, 2 factor for 3 agent, 3 for 1 agent
ACT_TABLE_LOG_HR_TEMP_START			= ACT_TABLE_LOG_HR_FLOORSTATUS + 1
ACT_TABLE_LOG_HR_LIGHT_START		= ACT_TABLE_LOG_HR_TEMP_START + 3
ACT_TABLE_LOG_HR_RESOURCES_START	= ACT_TABLE_LOG_HR_LIGHT_START + 3
ACT_TABLE_LOG_HR_WATER_START		= ACT_TABLE_LOG_HR_RESOURCES_START + 5
ACT_TABLE_LOG_HR_ELECTRICITY_START	= ACT_TABLE_LOG_HR_WATER_START + 2
ACT_TABLE_LOG_HR_GAS_START			= ACT_TABLE_LOG_HR_ELECTRICITY_START + (3 * 2)
ACT_TABLE_LOG_ABILITY				= ACT_TABLE_LOG_HR_GAS_START + 2
ACT_TABLE_LOG_EMO_TOTAL				= ACT_TABLE_LOG_ABILITY + 1
ACT_TABLE_LOG_EMO_CCE				= ACT_TABLE_LOG_EMO_TOTAL + 1
ACT_TABLE_LOG_FIS_HUNGER_START		= ACT_TABLE_LOG_EMO_CCE + 1
ACT_TABLE_LOG_FIS_DIRTY_START		= ACT_TABLE_LOG_FIS_HUNGER_START + 12
ACT_TABLE_LOG_FIS_THIRST_START		= ACT_TABLE_LOG_FIS_DIRTY_START + 10
ACT_TABLE_LOG_FIS_ENERGY_START		= ACT_TABLE_LOG_FIS_THIRST_START + 10
ACT_TABLE_LOG_FIS_EXHAUSTED_START	= ACT_TABLE_LOG_FIS_ENERGY_START + 10
ACT_TABLE_LOG_FIS_SLEEPY_START		= ACT_TABLE_LOG_FIS_EXHAUSTED_START + 8
ACT_TABLE_LOG_FIS_DEFECATE_START	= ACT_TABLE_LOG_FIS_SLEEPY_START + 11
ACT_TABLE_LOG_FIS_URINATE_START		= ACT_TABLE_LOG_FIS_DEFECATE_START + 18
ACT_TABLE_LOG_TOTAL					= ACT_TABLE_LOG_FIS_URINATE_START + 12

CP_ROOM = "CENTER"
RF_NONE				= 0

def clamp(value, minV, maxV):
	return max(minV,min(maxV,value))